# Step 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY GeneratorStores.API/*.csproj ./GeneratorStores.API/
COPY GeneratorStores.DataAccess/*.csproj ./GeneratorStores.DataAccess/
RUN dotnet restore

COPY . .
WORKDIR /src/GeneratorStores.API
RUN dotnet publish -c Release -o /app/publish

# Step 2: Use ASP.NET runtime to run the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "GeneratorStores.API.dll"]
